print('=== AUDIT SOUPLESSE COCKPIT ===')
print()
print('MODIFIABLE PAR L INTERFACE :')
print('  [OK] Jalons : marquer fait, annuler, saisir montant reel')
print('  [OK] Flux imprevu : ajouter entree/sortie libre')
print('  [OK] AAH : saisie annuelle')
print('  [OK] Devis artisans : montant, artisan, statut, paiement')
print('  [OK] Capital poches : via Saisie Capital')
print()
print('FIGE - PAS MODIFIABLE SANS PATCH :')
print('  [BLOQUE] Rail mensuel (2760 EUR)')
print('  [BLOQUE] Rendement annuel (3,5%)')
print('  [BLOQUE] Age cible (92 ans)')
print('  [BLOQUE] Versement parents (325 EUR)')
print('  [BLOQUE] Budget travaux total (33 000 EUR)')
print('  [BLOQUE] Loyer net (320 EUR)')
print('  [BLOQUE] Nombre de poches (7 fixes)')
print('  [BLOQUE] AAH mensuelle dans profil (1 033 EUR)')
print()
print('SOLUTION : creer une page Parametres modifiable')
