p='C:/Users/BoulePiou/cockpit-raphael/app.py'
f=open(p,'r',encoding='utf-8')
t=f.read()
f.close()
print('db_wrapper:', t.count('db_wrapper'))
print('sqlite3.connect:', t.count('sqlite3.connect'))
print('BoulePiou:', t.count('BoulePiou'))
print('stSidebar CSS:', t.count('stSidebar'))
print('collapsedControl:', t.count('collapsedControl'))
print('initial_sidebar_state:', 'expanded' if 'expanded' in t else 'collapsed')
